[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run ui:dev"
  targetPort = 5173
  port = 8888
  autoLaunch = false
